[build]
builder = "NIXPACKS"

[build.packages]
dotnet-sdk_8 = "latest"

[build.commands]
build = "dotnet publish BookHub.csproj -c Release -o out"

[deploy]
startCommand = "cd out && dotnet BookHub.dll"