[build]
builder = "NIXPACKS"

[build.packages]
dotnet-core = "8.0.416"

[build.commands]
build = "dotnet publish BookHub.csproj -c Release -o out"

[deploy]
startCommand = "cd out && dotnet BookHub.dll"